# -*- coding: utf-8 -*-
"""Actintegradora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQ_Y8Zyboi5oOzMZ2EfS0aWMYWD2Rahw

# Act Integradora
"""

import streamlit as st
import pandas as pd
st.title('Police Incident Reports from 2018 to 2020 in San Francisco')
df = pd.read_csv('https://drive.google.com/drive/folders/1Hd2HOFknGccrm11VSdDp5N9-ADkboWvZ')
st.markdown('The data shown below ')


mapa=pd.DataFrame()
mapa=mapa.dropna()
st.map(mapa.astype(int))

#import pandas as pd
#import streamlit as st
#import numpy as np

#import plotly as px

#import plotly.figure_factory as ff

#from bokeh.plotting import figure

#import matplotlib.pyplot as plt

#st.title( 'Police Incident Reports from 2018 to 2020 in San Francisco')

#df = pd.read_csv("Police_Department_Incident_Reports__2018_to_Present.csv")