# -*- coding: utf-8 -*-
"""pruebamapa2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQ_Y8Zyboi5oOzMZ2EfS0aWMYWD2Rahw

# Act Integradora
"""

import streamlit as st
import pandas as pd
import numpy as np
st.title('Police Incident Reports from 2018 to 2020 in San Francisco')
df = pd.read_csv('https://drive.google.com/drive/folders/1Hd2HOFknGccrm11VSdDp5N9-ADkboWvZ')
st.markdown('The data shown below ')


mapa=pd.DataFrame(
    np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],
    columns=['lat', 'lon'])
mapa = mapa.dropna()
st.map(mapa.astype(int))